require("autoclose").setup()
-- change default fast_wrap
--   filetypes = {
--     ['*'] = {
--       ['('] = {
--         kind = {
--           cmp.lsp.CompletionItemKind.Function,
--           cmp.lsp.CompletionItemKind.Method,
--         },
--       }
--     }
--   }
-- }))
